# ===================================
#  List Behavior Config
# ===================================

title: Permissions
list: ~/plugins/shahiemseymor/roles/models/permissions/columns.yaml
modelClass: ShahiemSeymor\Roles\Models\Permission
recordUrl: shahiemseymor/roles/permissions/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: yes

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt